---
title: "Prerequisites"
author: "Emma Rand and Ian Lyttle"
format: html
execute:
  echo: true
  eval: false
bibliography: references.bib
---

You will need:

-   [R and RStudio](#install-r-and-rstudio)  
-   To [install some packages](#packages) 
-   To connect to [Discord](#discord), for in-class interaction

## Install R and RStudio {#install-r-and-rstudio}

We will use:

-   R version \>= 4.3
-   RStudio \>= 2023.03.1

## Install packages {#packages}

Most of the packages we use are imported by **`tidyverse`** and **`devtools`**:

``` r
install.packages(c("devtools", "tidyverse", "palmerpenguins", "here"))
```

In case of any installation problems, you will also have access to a Posit Cloud hosted RStudio project.

## Discord {#discord}

During the workshop we will have experienced helpers to troubleshoot and will use Discord to enhance workshop interactions: 

- [Please sign up for an account](https://discord.com/) if you don’t already have one.
- Make sure your [display name](https://support.discord.com/hc/en-us/articles/12620128861463-New-Usernames-Display-Names#h_01GXPQABMYGEHGPRJJXJMPHF5C) is the one you used to register for the conference.
- In your “About Me”, put the name of your workshop(s).

Closer to the start of the conference, we will invite you to the posit::conf Discord server. Once you’ve accepted the invitation, we will add you to the channel(s) for your conference workshop(s).
